name: Bug Report
description: File a bug report
title: '[BUG]: '
labels: ['bug']
assignees:
  - Sayshal
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report an issue with the module. Please fill out all the fields to the best of your ability.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: What version of the package?
      placeholder: '1.0.0'
    validations:
      required: true
  - type: input
    id: core-version
    attributes:
      label: Foundry Version
      description: What version of foundry?
      placeholder: '12.331'
    validations:
      required: true
  - type: input
    id: system-version
    attributes:
      label: D&D Version
      description: What version of the system?
      placeholder: '3.3.1'
    validations:
      required: true
  - type: checkboxes
    id: troubleshooter
    attributes:
      label: Hero Mancer Troubleshooter
      description: Recreate the issue being reported in Hero Mancer, and without closing the application, open the troubleshooter from the Settings menu. Download the troubleshooter file and include it as a comment after creating this issue.
      options:
        - label: I understand that I will not recieve support until a troubleshooter file has been uploaded.
    validations:
      required: true
